apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.gitops.repoUrl }}
    targetRevision: {{ .Values.gitops.targetRevision }}
    path: {{ .Values.gitops.path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true