apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: url-shortener
  namespace: argocd
spec:
  description: URL Shortener Project
  sourceRepos:
    - https://github.com/your-org/gitops-config.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'